CLUSTER=debezium
NAMESPACE=debezium
TIMEOUT=720s

DBZ_INSTALL_OPERATOR=true
DBZ_OPERATOR_VERSION=3.0.0-final

STRIMZI_INSTALL_OPERATOR=true
STRIMZI_OPERATOR_VERSION=0.44.0
STRIMZI_DEPLOY_KAFKA=true

POSTGRES_DEPLOY=true


