services:
  conductor:
    image: quay.io/debezium/platform-conductor:nightly
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_USERNAME: conductor
      QUARKUS_DATASOURCE_PASSWORD: conductor
      QUARKUS_DATASOURCE_JDBC_URL:  jdbc:postgresql://postgres:5432/conductor
  postgres:
    image: quay.io/debezium/postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: conductor
      POSTGRES_PASSWORD: conductor
      POSTGRES_DB: conductor