apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: conductor
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: debezium-platform
{{ include "common.labels" . | indent 4 }}
  name: conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: conductor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: conductor
    spec:
      serviceAccountName: conductor-service-account
      containers:
        - env:
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "debezium-platform.secretName" . }}
                  key: password
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "debezium-platform.secretName" . }}
                  key: username
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote}}
            {{- end }}
          image: {{ .Values.conductor.image }}
          name: conductor
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always