apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: conductor
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: debezium-platform
    app.kubernetes.io/managed-by: Helm
  name: conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: conductor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: conductor
    spec:
      serviceAccountName: conductor-service-account
      containers:
        - env:
            - name: CONDUCTOR_WATCHER_ENABLED
              value: "true"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://{{ .Values.database.host }}:5432/{{ .Values.database.name }}
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: {{ .Values.database.password }}
            - name: QUARKUS_DATASOURCE_USERNAME
              value: {{ .Values.database.username }}
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: http://{{ .Values.domain.url }}
            - name: QUARKUS_KUBERNETES_CLIENT_NAMESPACE
              value: {{ .Release.Namespace }}
          image: {{ .Values.api.image }}
          name: conductor
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always