conductor:
  watcher:
    enabled: true
    offset:
      storage:
        type: org.apache.kafka.connect.storage.FileOffsetBackingStore
        config:
          file:
            filename: offsets.dat
      config:
        flush:
          interval:
            ms: 300

quarkus:
  http:
    cors:
        ~: true
  debezium-outbox:
    table-name: events
    aggregate-type:
      name: aggregatetype
    aggregate-id:
      name: aggregateid
    type:
      name: type
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      #   We should use Flyway or Liquibase for schema migration
      generation: update
  swagger-ui:
    always-include: true
  log:
    level: INFO

"%dev":
  conductor:
    watcher:
      enabled: true
      crd: https://raw.githubusercontent.com/debezium/debezium-operator/main/k8/debeziumservers.debezium.io-v1.yml
      offset:
        storage:
          type: org.apache.kafka.connect.storage.FileOffsetBackingStore
          config:
            file:
              filename: offsets.dat
        config:
          flush:
            interval:
              ms: 300
  quarkus:
    debezium-outbox:
      remove-after-insert: false
    datasource:
      devservices:
        enabled: true
        port: 5432
        image-name: quay.io/debezium/postgres:16-alpine
    http:
      port: 8081
    log:
      level: INFO
      category:
        "io.debezium": DEBUG