domain:
  url: ""
stage:
  image: quay.io/debezium/platform-stage:latest
conductor:
  image: quay.io/debezium/platform-conductor:nightly
  offset:
    existingConfigMap: ""
kafka:
  enabled: false
database:
  enabled: false
  name: postgres
  host: postgres
  auth:
    existingSecret: ""
env:
  QUARKUS_KUBERNETES_CLIENT_NAMESPACE: "{{ .Release.Namespace }}"