domain:
  url: platform.debezium.io
stage:
  image: quay.io/debezium/platform-stage:latest
api:
  image: quay.io/debezium/platform-conductor:nightly
kafka:
  enabled: false
database:
  enabled: false
  name: postgres
  host: postgres
  auth:
    existingSecret: ""